/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-light': 'var(--color-primary-light)',
        accent: 'var(--color-accent)',
        'bg-main': 'var(--color-bg-main)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'bg-section': 'var(--color-bg-section)',
        'bg-card': 'var(--color-bg-card)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'text-placeholder': 'var(--color-text-placeholder)',
        'border-light': 'var(--color-border-light)',
        'border-medium': 'var(--color-border-medium)',
        'border-card': 'var(--color-border-card)',
        'btn-primary': 'var(--color-btn-primary)',
        'btn-hover': 'var(--color-btn-hover)',
        'btn-text': 'var(--color-btn-text)',
        'btn-secondary': 'var(--color-btn-secondary)',
        'btn-secondary-border': 'var(--color-btn-secondary-border)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        error: 'var(--color-error)',
        info: 'var(--color-info)',
        'navbar-bg': 'var(--color-navbar-bg)',
        'sidebar-bg': 'var(--color-sidebar-bg)',
        'menu-active': 'var(--color-menu-active)',
        'menu-inactive': 'var(--color-menu-inactive)',
        'menu-hover-bg': 'var(--color-menu-hover-bg)',
        'card-hover-border': 'var(--color-card-hover-border)',
        'input-bg': 'var(--color-input-bg)',
        'input-border': 'var(--color-input-border)',
        'input-focus': 'var(--color-input-focus)',
        'input-placeholder': 'var(--color-input-placeholder)',
        'chart-primary': 'var(--color-chart-primary)',
        'chart-light': 'var(--color-chart-light)',
        'progress-bg': 'var(--color-progress-bg)',
        'progress-fill': 'var(--color-progress-fill)',
        // Keep fallback maps for old colors so unchanged pages don't crash
        accentSoft: 'var(--color-accent)',
        textPrimary: 'var(--color-text-primary)',
        textSecondary: 'var(--color-text-secondary)',
        textMuted: 'var(--color-text-muted)',
        bg: 'var(--color-bg-main)',
        surface: 'var(--color-bg-card)',
        surfaceAlt: 'var(--color-bg-secondary)',
        border: 'var(--color-border-card)',
        borderFocus: 'var(--color-input-focus)',
      },
      fontFamily: {
        sans: ['"Segoe UI"', 'Segoe UI', 'sans-serif'],
      },
      borderRadius: {
        card: 'var(--radius-card)',
        pill: '999px',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        accent: '0 0 14px rgba(37, 99, 235, 0.18)',
      },
    },
  },
  plugins: [],
}
