-- =========================================================================
-- SEED: 70+ REAL COURSES ACROSS ALL DOMAINS
-- Run AFTER 001_courses_expansion.sql
-- =========================================================================

INSERT INTO courses (title, description, provider, platform, url, difficulty, price, rating, duration_weeks, category, language, instructor, tags, prerequisites, learning_outcomes, skill_id) VALUES

-- ===== SOFTWARE DEVELOPMENT (12 courses) =====
('JavaScript: The Advanced Concepts', 'Deep dive into closures, prototypes, event loop, and advanced JS patterns.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/advanced-javascript-concepts/', 'Advanced', '₹455', 4.7, 8, 'Software Development', 'English', 'Jonas Schmedtmann', ARRAY['javascript','advanced','closures','async'], ARRAY['Basic JavaScript knowledge'], ARRAY['Master closures and scope chain','Understand the event loop','Work with async/await patterns'], NULL),
('Introduction to Javascript', 'Learn the fundamentals of JavaScript from scratch.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/javascript', 'Beginner', 'Free', 4.6, 6, 'Software Development', 'English', 'University of Michigan', ARRAY['javascript','beginner','web'], ARRAY['No prior experience needed'], ARRAY['Write JavaScript programs','Use DOM manipulation','Build interactive web pages'], NULL),
('React - The Complete Guide', 'Build powerful React apps with hooks, Redux, and Next.js.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/react-the-complete-guide/', 'Intermediate', '₹499', 4.7, 12, 'Software Development', 'English', 'Maximilian Schwarzmüller', ARRAY['react','hooks','redux','nextjs'], ARRAY['JavaScript fundamentals','HTML & CSS basics'], ARRAY['Build full React applications','Manage state with hooks and Redux','Use Next.js for SSR'], NULL),
('Node.js, Express, MongoDB & More', 'Complete backend development with Node.js ecosystem.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/nodejs-express-mongodb/', 'Intermediate', '₹499', 4.6, 10, 'Software Development', 'English', 'Jonas Schmedtmann', ARRAY['nodejs','express','mongodb','rest-api'], ARRAY['JavaScript knowledge','Basic HTML/CSS'], ARRAY['Build REST APIs with Express','Work with MongoDB','Deploy Node apps'], NULL),
('Meta Front-End Developer Professional Certificate', 'Professional front-end development with React from Meta.', 'Coursera', 'Coursera', 'https://www.coursera.org/professional-certificates/meta-front-end-developer', 'Beginner', '₹4,999/mo', 4.8, 24, 'Software Development', 'English', 'Meta Engineering', ARRAY['react','html','css','javascript','frontend'], ARRAY['No experience needed'], ARRAY['Build responsive web apps','Master React and JavaScript','Prepare for front-end roles'], NULL),
('IBM Full Stack Software Developer', 'Become a full-stack developer with cloud-native tools.', 'Coursera', 'Coursera', 'https://www.coursera.org/professional-certificates/ibm-full-stack-cloud-developer', 'Beginner', '₹4,999/mo', 4.6, 28, 'Software Development', 'English', 'IBM', ARRAY['fullstack','cloud','docker','kubernetes','react'], ARRAY['Basic programming knowledge'], ARRAY['Build cloud-native apps','Use Docker and Kubernetes','Develop with React and Node.js'], NULL),
('TypeScript for React Developers', 'Add type safety to your React applications with TypeScript.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/typescript-for-react/', 'Intermediate', '₹399', 4.5, 5, 'Software Development', 'English', 'Maximilian Schwarzmüller', ARRAY['typescript','react','types'], ARRAY['React basics','JavaScript fundamentals'], ARRAY['Type React components','Use generics and utility types','Build type-safe apps'], NULL),
('Vue.js 3 - The Complete Guide', 'Build modern web apps with Vue 3, Composition API, and Pinia.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/vuejs-3-the-complete-guide/', 'Beginner', '₹455', 4.7, 10, 'Software Development', 'English', 'Maximilian Schwarzmüller', ARRAY['vue','javascript','frontend','composition-api'], ARRAY['HTML, CSS, JavaScript basics'], ARRAY['Build Vue 3 apps','Use Composition API','State management with Pinia'], NULL),
('Angular - The Complete Guide', 'Master Angular and build professional web applications.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/the-complete-guide-to-angular-2/', 'Intermediate', '₹499', 4.6, 14, 'Software Development', 'English', 'Maximilian Schwarzmüller', ARRAY['angular','typescript','frontend','rxjs'], ARRAY['JavaScript knowledge','TypeScript basics helpful'], ARRAY['Build large Angular apps','Use services, pipes, directives','Deploy Angular applications'], NULL),
('Django Web Framework', 'Build full-stack web applications with Python and Django.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/django-web-framework', 'Intermediate', 'Free', 4.5, 6, 'Software Development', 'English', 'University of Michigan', ARRAY['python','django','web','backend'], ARRAY['Python programming','Basic HTML'], ARRAY['Build Django web apps','Use ORM and models','Create REST APIs with Django'], NULL),
('Java Programming Masterclass', 'Learn Java from basics to advanced OOP and beyond.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/java-the-complete-java-developer-course/', 'Beginner', '₹499', 4.6, 20, 'Software Development', 'English', 'Tim Buchalka', ARRAY['java','oop','programming','backend'], ARRAY['No programming experience needed'], ARRAY['Master Java fundamentals','Build OOP applications','Work with files and streams'], NULL),
('Go Programming Bootcamp', 'Learn Go from scratch — build web apps, CLIs, and microservices.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/learn-go-the-complete-bootcamp-course-golang/', 'Beginner', '₹455', 4.7, 10, 'Software Development', 'English', 'Jose Portilla', ARRAY['go','golang','backend','microservices'], ARRAY['Basic programming knowledge'], ARRAY['Write Go programs','Build web servers','Create CLI tools'], NULL),

-- ===== DATA SCIENCE & AI (12 courses) =====
('Python for Everybody Specialization', 'Learn Python programming and data analysis fundamentals.', 'Coursera', 'Coursera', 'https://www.coursera.org/specializations/python-for-everybody', 'Beginner', 'Free', 4.7, 20, 'Data Science', 'English', 'University of Michigan', ARRAY['python','data','beginner','analysis'], ARRAY['No prior experience needed'], ARRAY['Write Python programs','Parse and analyze data','Use Python for research'], NULL),
('Machine Learning Specialization', 'Andrew Ng''s classic ML course — updated for Python.', 'Coursera', 'Coursera', 'https://www.coursera.org/specializations/machine-learning-introduction', 'Intermediate', '₹4,999/mo', 4.9, 16, 'Data Science', 'English', 'Andrew Ng (DeepLearning.AI)', ARRAY['machine-learning','python','tensorflow','supervised'], ARRAY['Python programming','Basic statistics'], ARRAY['Build ML models','Use TensorFlow','Apply supervised and unsupervised learning'], NULL),
('Deep Learning Specialization', 'Master deep learning — CNNs, RNNs, Transformers, and more.', 'Coursera', 'Coursera', 'https://www.coursera.org/specializations/deep-learning', 'Advanced', '₹4,999/mo', 4.8, 20, 'Data Science', 'English', 'Andrew Ng (DeepLearning.AI)', ARRAY['deep-learning','neural-networks','cnn','rnn','transformers'], ARRAY['Machine learning knowledge','Python and NumPy'], ARRAY['Build deep learning models','Implement CNNs and RNNs','Work with Transformers'], NULL),
('Google Data Analytics Professional Certificate', 'Job-ready data analytics skills from Google.', 'Coursera', 'Coursera', 'https://www.coursera.org/professional-certificates/google-data-analytics', 'Beginner', '₹4,999/mo', 4.8, 24, 'Data Science', 'English', 'Google', ARRAY['data-analytics','sql','spreadsheets','tableau'], ARRAY['No experience needed'], ARRAY['Analyze data with SQL and spreadsheets','Create data visualizations','Prepare for analytics roles'], NULL),
('IBM Data Science Professional Certificate', 'Launch your career in data science with IBM.', 'Coursera', 'Coursera', 'https://www.coursera.org/professional-certificates/ibm-data-science', 'Beginner', '₹4,999/mo', 4.6, 28, 'Data Science', 'English', 'IBM', ARRAY['data-science','python','sql','machine-learning'], ARRAY['No experience needed'], ARRAY['Use Python for data science','Apply SQL for data analysis','Build ML models with scikit-learn'], NULL),
('Data Engineering with Google Cloud', 'Build data pipelines and warehouses on Google Cloud.', 'Coursera', 'Coursera', 'https://www.coursera.org/professional-certificates/data-engineering', 'Intermediate', '₹4,999/mo', 4.6, 16, 'Data Science', 'English', 'Google Cloud', ARRAY['data-engineering','gcp','bigquery','pipelines'], ARRAY['Basic SQL','Python programming'], ARRAY['Design data pipelines','Use BigQuery','Build data warehouses on GCP'], NULL),
('Natural Language Processing Specialization', 'Master NLP — from text processing to Transformers and LLMs.', 'Coursera', 'Coursera', 'https://www.coursera.org/specializations/natural-language-processing', 'Advanced', '₹4,999/mo', 4.6, 16, 'Data Science', 'English', 'DeepLearning.AI', ARRAY['nlp','transformers','bert','gpt','text'], ARRAY['Deep learning knowledge','Python and TensorFlow'], ARRAY['Build NLP pipelines','Fine-tune Transformer models','Work with word embeddings'], NULL),
('Statistics with Python Specialization', 'Master statistical analysis using Python.', 'Coursera', 'Coursera', 'https://www.coursera.org/specializations/statistics-with-python', 'Beginner', '₹4,999/mo', 4.7, 12, 'Data Science', 'English', 'University of Michigan', ARRAY['statistics','python','probability','regression'], ARRAY['Basic math knowledge'], ARRAY['Perform hypothesis testing','Build regression models','Analyze data statistically'], NULL),
('MLOps Specialization', 'Deploy and manage ML models in production.', 'Coursera', 'Coursera', 'https://www.coursera.org/specializations/machine-learning-engineering', 'Advanced', '₹4,999/mo', 4.5, 12, 'Data Science', 'English', 'DeepLearning.AI', ARRAY['mlops','deployment','docker','ci-cd','monitoring'], ARRAY['Machine learning experience','Python programming'], ARRAY['Deploy ML models','Build ML pipelines','Monitor model performance'], NULL),

-- ===== CLOUD & DEVOPS (8 courses) =====
('AWS Cloud Practitioner Essentials', 'Start your cloud journey with Amazon Web Services.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/aws-cloud-practitioner-essentials', 'Beginner', 'Free', 4.7, 4, 'Cloud & DevOps', 'English', 'Amazon Web Services', ARRAY['aws','cloud','iam','ec2','s3'], ARRAY['No prerequisites'], ARRAY['Understand AWS core services','Design basic cloud architecture','Prepare for AWS certification'], NULL),
('Google Cloud Digital Leader', 'Learn Google Cloud fundamentals and earn a certification.', 'Coursera', 'Coursera', 'https://www.coursera.org/professional-certificates/google-cloud-digital-leader', 'Beginner', '₹4,999/mo', 4.6, 12, 'Cloud & DevOps', 'English', 'Google Cloud', ARRAY['gcp','cloud','compute','storage','networking'], ARRAY['No prerequisites'], ARRAY['Navigate Google Cloud console','Understand cloud services','Prepare for GCP certification'], NULL),
('Microsoft Azure Fundamentals', 'Get started with Microsoft Azure cloud services.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/azure-fundamentals', 'Beginner', 'Free', 4.6, 4, 'Cloud & DevOps', 'English', 'Microsoft', ARRAY['azure','cloud','virtual-machines','storage'], ARRAY['Basic IT knowledge'], ARRAY['Understand Azure services','Manage Azure resources','Prepare for AZ-900 exam'], NULL),
('Docker & Kubernetes: The Complete Guide', 'Containerize apps and orchestrate with Kubernetes.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/docker-kubernetes-the-complete-guide/', 'Intermediate', '₹499', 4.7, 12, 'Cloud & DevOps', 'English', 'Stephen Grider', ARRAY['docker','kubernetes','containers','devops'], ARRAY['Basic command line','Node.js or Python basics'], ARRAY['Build Docker images','Deploy with Kubernetes','Create microservice architectures'], NULL),
('Terraform for Beginners', 'Infrastructure as Code with HashiCorp Terraform.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/terraform-for-beginners/', 'Beginner', '₹399', 4.5, 5, 'Cloud & DevOps', 'English', 'Bryan Krausen', ARRAY['terraform','iac','aws','infrastructure'], ARRAY['Basic cloud knowledge'], ARRAY['Write Terraform configurations','Manage cloud infrastructure','Use state and modules'], NULL),
('CI/CD Pipeline with Jenkins and GitHub Actions', 'Automate your build, test, and deployment workflows.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/ciccd-pipeline-jenkins-github-actions/', 'Intermediate', '₹399', 4.4, 5, 'Cloud & DevOps', 'English', 'Valentin Despa', ARRAY['ci-cd','jenkins','github-actions','automation'], ARRAY['Git basics','Basic DevOps knowledge'], ARRAY['Build CI/CD pipelines','Use Jenkins and GitHub Actions','Automate deployments'], NULL),
('Linux Administration Bootcamp', 'Master Linux command line and server administration.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/linux-administration-bootcamp/', 'Beginner', '₹399', 4.6, 8, 'Cloud & DevOps', 'English', 'Jason Cannon', ARRAY['linux','command-line','shell','administration'], ARRAY['No Linux experience needed'], ARRAY['Navigate Linux command line','Manage users and permissions','Administer Linux servers'], NULL),
('Git & GitHub Crash Course', 'Master version control with Git and GitHub.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/git-and-github-crash-course/', 'Beginner', '₹349', 4.5, 3, 'Cloud & DevOps', 'English', 'Jason Cannon', ARRAY['git','github','version-control','collaboration'], ARRAY['No prerequisites'], ARRAY['Use Git for version control','Collaborate on GitHub','Manage branches and merges'], NULL),

-- ===== CYBERSECURITY (6 courses) =====
('Introduction to Cybersecurity', 'Learn cybersecurity fundamentals and threat landscape.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/intro-cybersecurity', 'Beginner', 'Free', 4.7, 4, 'Cybersecurity', 'English', 'IBM', ARRAY['cybersecurity','threats','encryption','networks'], ARRAY['No prerequisites'], ARRAY['Understand cyber threats','Apply encryption basics','Protect networks and systems'], NULL),
('Google Cybersecurity Professional Certificate', 'Job-ready cybersecurity skills from Google.', 'Coursera', 'Coursera', 'https://www.coursera.org/professional-certificates/google-cybersecurity', 'Beginner', '₹4,999/mo', 4.7, 20, 'Cybersecurity', 'English', 'Google', ARRAY['cybersecurity','siem','python','linux','networks'], ARRAY['No experience needed'], ARRAY['Identify and mitigate threats','Use SIEM tools','Analyze network traffic'], NULL),
('Ethical Hacking Essentials', 'Learn penetration testing and ethical hacking basics.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/ethical-hacking-essentials/', 'Beginner', '₹399', 4.5, 6, 'Cybersecurity', 'English', 'Nathan House', ARRAY['hacking','pentesting','security','networks'], ARRAY['Basic networking knowledge'], ARRAY['Perform basic penetration tests','Understand attack vectors','Secure web applications'], NULL),
('CompTIA Security+ Certification', 'Prepare for the SY0-601 Security+ exam.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/comptia-security-plus/', 'Intermediate', '₹455', 4.7, 12, 'Cybersecurity', 'English', 'Jason Dion', ARRAY['security','compliance','risk','cryptography'], ARRAY['Basic IT knowledge','Network fundamentals'], ARRAY['Pass the Security+ exam','Manage risk and compliance','Implement security controls'], NULL),
('Python for Cybersecurity', 'Use Python to automate security tasks and analysis.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/python-for-cybersecurity', 'Intermediate', 'Free', 4.5, 4, 'Cybersecurity', 'English', 'IBM', ARRAY['python','security','automation','scripting'], ARRAY['Basic Python knowledge'], ARRAY['Write security scripts','Automate security analysis','Parse logs and network data'], NULL),
('Network Security & Database Vulnerabilities', 'Protect networks and databases from cyber attacks.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/network-security-database-vulnerabilities', 'Intermediate', 'Free', 4.4, 4, 'Cybersecurity', 'English', 'IBM', ARRAY['network-security','firewalls','databases','vulnerabilities'], ARRAY['Basic networking','IT fundamentals'], ARRAY['Configure firewalls','Secure databases','Identify network vulnerabilities'], NULL),

-- ===== BUSINESS & MANAGEMENT (6 courses) =====
('Google Project Management Professional Certificate', 'Launch your career in project management.', 'Coursera', 'Coursera', 'https://www.coursera.org/professional-certificates/google-project-management', 'Beginner', '₹4,999/mo', 4.8, 24, 'Business & Management', 'English', 'Google', ARRAY['project-management','agile','scrum','stakeholders'], ARRAY['No experience needed'], ARRAY['Manage projects using Agile','Create project documentation','Lead effective teams'], NULL),
('Business Analytics Specialization', 'Make data-driven business decisions with analytics.', 'Coursera', 'Coursera', 'https://www.coursera.org/specializations/business-analytics', 'Beginner', '₹4,999/mo', 4.6, 16, 'Business & Management', 'English', 'University of Pennsylvania', ARRAY['analytics','excel','data','business','decision-making'], ARRAY['Basic math knowledge'], ARRAY['Analyze business data','Build financial models','Make data-driven decisions'], NULL),
('Digital Marketing Specialization', 'Master digital marketing strategy and execution.', 'Coursera', 'Coursera', 'https://www.coursera.org/specializations/digital-marketing', 'Beginner', '₹4,999/mo', 4.6, 16, 'Business & Management', 'English', 'University of Illinois', ARRAY['digital-marketing','seo','social-media','analytics'], ARRAY['No prerequisites'], ARRAY['Create digital marketing strategies','Run SEO and SEM campaigns','Measure marketing ROI'], NULL),
('Financial Management Specialization', 'Learn corporate finance and investment fundamentals.', 'Coursera', 'Coursera', 'https://www.coursera.org/specializations/financial-management', 'Intermediate', '₹4,999/mo', 4.5, 16, 'Business & Management', 'English', 'University of Illinois', ARRAY['finance','investment','accounting','valuation'], ARRAY['Basic math and economics'], ARRAY['Value companies and assets','Manage corporate finance','Build investment portfolios'], NULL),
('Google Digital Marketing & E-commerce Certificate', 'Job-ready digital marketing and e-commerce skills.', 'Coursera', 'Coursera', 'https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce', 'Beginner', '₹4,999/mo', 4.7, 18, 'Business & Management', 'English', 'Google', ARRAY['marketing','e-commerce','analytics','ads','seo'], ARRAY['No experience needed'], ARRAY['Plan and execute e-commerce strategy','Run Google Ads campaigns','Analyze marketing metrics'], NULL),
('Supply Chain Management Specialization', 'Optimize supply chains with analytics and strategy.', 'Coursera', 'Coursera', 'https://www.coursera.org/specializations/supply-chain-management', 'Intermediate', '₹4,999/mo', 4.6, 20, 'Business & Management', 'English', 'Rutgers University', ARRAY['supply-chain','logistics','operations','analytics'], ARRAY['Basic business knowledge'], ARRAY['Design supply chain networks','Optimize logistics','Use analytics for operations'], NULL),

-- ===== DESIGN & UX (6 courses) =====
('Google UX Design Professional Certificate', 'Job-ready UX design skills from Google.', 'Coursera', 'Coursera', 'https://www.coursera.org/professional-certificates/google-ux-design', 'Beginner', '₹4,999/mo', 4.8, 24, 'Design & UX', 'English', 'Google', ARRAY['ux-design','figma','wireframes','user-research','prototyping'], ARRAY['No experience needed'], ARRAY['Conduct user research','Build wireframes and prototypes','Design responsive web and mobile apps'], NULL),
('UI/UX Design Specialization', 'Create user-centered interfaces and experiences.', 'Coursera', 'Coursera', 'https://www.coursera.org/specializations/ui-ux-design', 'Beginner', '₹4,999/mo', 4.5, 16, 'Design & UX', 'English', 'University of Minnesota', ARRAY['ui','ux','design','usability','accessibility'], ARRAY['No prerequisites'], ARRAY['Apply UX design principles','Create accessible interfaces','Conduct usability testing'], NULL),
('Figma for UI/UX Design', 'Master Figma — the industry-standard design tool.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/figma-for-ui-ux-design/', 'Beginner', '₹399', 4.6, 6, 'Design & UX', 'English', 'Daniel Scott', ARRAY['figma','ui','ux','prototyping','design-systems'], ARRAY['No prerequisites'], ARRAY['Design interfaces in Figma','Build design systems','Create interactive prototypes'], NULL),
('Graphic Design Specialization', 'Learn visual design fundamentals — typography, color, layout.', 'Coursera', 'Coursera', 'https://www.coursera.org/specializations/graphic-design', 'Beginner', '₹4,999/mo', 4.6, 16, 'Design & UX', 'English', 'CalArts', ARRAY['graphic-design','typography','color','layout','branding'], ARRAY['No prerequisites'], ARRAY['Apply design principles','Create visual compositions','Build brand identities'], NULL),
('Motion Design for UI', 'Create animations and micro-interactions for web and mobile.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/motion-design-for-ui/', 'Intermediate', '₹399', 4.4, 5, 'Design & UX', 'English', 'Daniel Scott', ARRAY['motion','animation','after-effects','ui','lottie'], ARRAY['Basic design knowledge','Figma or Sketch experience'], ARRAY['Create UI animations','Use After Effects for web','Export animations with Lottie'], NULL),
('Adobe Photoshop Masterclass', 'Complete photo editing and graphic design with Photoshop.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/adobe-photoshop-masterclass/', 'Beginner', '₹455', 4.6, 10, 'Design & UX', 'English', 'Phil Ebiner', ARRAY['photoshop','photo-editing','design','retouching'], ARRAY['No prerequisites'], ARRAY['Edit and retouch photos','Create graphic designs','Use layers and masks'], NULL),

-- ===== MOBILE DEVELOPMENT (5 courses) =====
('iOS & Swift - The Complete iOS App Development', 'Build iOS apps from scratch with Swift and SwiftUI.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/ios-13-app-development-bootcamp/', 'Beginner', '₹499', 4.7, 16, 'Mobile Development', 'English', 'Angela Yu', ARRAY['ios','swift','swiftui','xcode','mobile'], ARRAY['No iOS experience needed','Basic programming knowledge'], ARRAY['Build iOS apps with Swift','Use SwiftUI for interfaces','Publish apps to App Store'], NULL),
('The Complete Android Developer Guide', 'Build modern Android apps with Kotlin and Jetpack Compose.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/the-complete-android-developer-guide/', 'Beginner', '₹455', 4.6, 12, 'Mobile Development', 'English', 'Philipp Muellner', ARRAY['android','kotlin','jetpack','mobile','compose'], ARRAY['Basic programming knowledge'], ARRAY['Build Android apps with Kotlin','Use Jetpack Compose','Publish to Google Play'], NULL),
('React Native - The Practical Guide', 'Build cross-platform mobile apps with React Native.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/react-native-the-practical-guide/', 'Intermediate', '₹455', 4.6, 10, 'Mobile Development', 'English', 'Maximilian Schwarzmüller', ARRAY['react-native','mobile','javascript','cross-platform'], ARRAY['React knowledge','JavaScript fundamentals'], ARRAY['Build cross-platform apps','Use native device features','Deploy to both app stores'], NULL),
('Flutter & Dart - The Complete Guide', 'Build beautiful native apps with Flutter and Dart.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/learn-flutter-dart-the-complete-guide/', 'Beginner', '₹455', 4.7, 14, 'Mobile Development', 'English', 'Maximilian Schwarzmüller', ARRAY['flutter','dart','mobile','cross-platform','widgets'], ARRAY['No mobile development experience'], ARRAY['Build Flutter apps','Use Dart programming','Create responsive mobile UIs'], NULL),
('Kotlin for Android Development', 'Master Kotlin programming for modern Android apps.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/kotlin-for-android-development', 'Intermediate', 'Free', 4.5, 6, 'Mobile Development', 'English', 'Vanderbilt University', ARRAY['kotlin','android','oop','mobile'], ARRAY['Basic programming knowledge'], ARRAY['Write Kotlin programs','Apply OOP in Kotlin','Build Android apps with Kotlin'], NULL),

-- ===== BLOCKCHAIN & WEB3 (3 courses) =====
('Blockchain Basics', 'Understand blockchain technology and its applications.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/blockchain-basics', 'Beginner', 'Free', 4.6, 4, 'Blockchain & Web3', 'English', 'University at Buffalo', ARRAY['blockchain','cryptocurrency','smart-contracts','decentralized'], ARRAY['No prerequisites'], ARRAY['Understand blockchain architecture','Explain cryptocurrency concepts','Identify blockchain use cases'], NULL),
('Ethereum and Solidity: Full Stack DApp Development', 'Build decentralized applications on Ethereum.', 'Udemy', 'Udemy', 'https://www.udemy.com/course/ethereum-and-solidity-the-complete-developers-guide/', 'Intermediate', '₹455', 4.6, 10, 'Blockchain & Web3', 'English', 'Jonas Schmedtmann', ARRAY['ethereum','solidity','smart-contracts','web3','dapp'], ARRAY['JavaScript knowledge','Basic blockchain understanding'], ARRAY['Write Solidity smart contracts','Build DApps with web3.js','Deploy to Ethereum'], NULL),
('NFTs and the Metaverse: Building Web3 Projects', 'Create NFT projects and explore the metaverse.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/nfts-metaverse-building-web3', 'Intermediate', 'Free', 4.3, 4, 'Blockchain & Web3', 'English', 'University at Buffalo', ARRAY['nft','metaverse','web3','ipfs','smart-contracts'], ARRAY['Basic programming','Blockchain fundamentals'], ARRAY['Create and deploy NFTs','Build metaverse experiences','Use IPFS for decentralized storage'], NULL),

-- ===== PRODUCTIVITY & SOFT SKILLS (4 courses) =====
('Learning How to Learn', 'Master the art of effective learning.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/learning-how-to-learn', 'Beginner', 'Free', 4.9, 4, 'Productivity & Soft Skills', 'English', 'UC San Diego', ARRAY['learning','memory','focus','creativity'], ARRAY['No prerequisites'], ARRAY['Use effective study techniques','Overcome procrastination','Improve memory retention'], NULL),
('Successful Negotiation: Essential Strategies', 'Master negotiation skills for career and life.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/negotiation-skills', 'Beginner', 'Free', 4.8, 6, 'Productivity & Soft Skills', 'English', 'University of Michigan', ARRAY['negotiation','communication','strategy','conflict'], ARRAY['No prerequisites'], ARRAY['Apply negotiation strategies','Handle difficult negotiations','Negotiate contracts and deals'], NULL),
('Presentation Skills: Design and Delivery', 'Create and deliver impactful presentations.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/presentation-skills', 'Beginner', 'Free', 4.5, 4, 'Productivity & Soft Skills', 'English', 'University of Washington', ARRAY['presentation','public-speaking','design','communication'], ARRAY['No prerequisites'], ARRAY['Design effective slides','Deliver confident presentations','Structure compelling narratives'], NULL),
('Teamwork Skills: Communicating Effectively', 'Build teamwork and communication skills.', 'Coursera', 'Coursera', 'https://www.coursera.org/learn/teamwork-skills-communicating-effectively', 'Beginner', 'Free', 4.4, 4, 'Productivity & Soft Skills', 'English', 'University of Colorado', ARRAY['teamwork','communication','collaboration','leadership'], ARRAY['No prerequisites'], ARRAY['Communicate in teams','Resolve conflicts','Lead group projects'], NULL);
